### ISSUE TITLE
Expr does not compile on Elixir 1.9.2

### ISSUE THREAD

**Issue by snunezcr** [Rob-bie/expr#8]
Just installed the package in 1.9.2 and got this:

== Compilation error in file lib/expr/ops.ex ==
** (CompileError) lib/expr/ops.ex:14: Expr.Ops.__struct__/1 is undefined, cannot expand struct Expr.Ops
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

**Comment by bortzmeyer** [comment]
It works for me with Elixir 1.12.2 (but with many warnings because of function calls without parenthesis).
