### ISSUE TITLE
Expr does not compile on Elixir 1.3.1

### ISSUE THREAD

**Issue by dongmaster** [Rob-bie/expr#6]
```
==> expr
Compiling 5 files (.ex)

== Compilation error on file lib/expr/parser.ex ==
** (CompileError)  deadlocked waiting on module Expr.Ops
    (elixir) src/elixir_aliases.erl:80: :elixir_aliases.ensure_loaded/3


== Compilation error on file lib/expr/ops.ex ==
** (CompileError)  deadlocked waiting on module Expr.Ops
    (stdlib) lists.erl:1353: :lists.mapfoldl/3


== Compilation error on file lib/expr.ex ==
** (CompileError)  deadlocked waiting on module Expr.Ops
    (elixir) src/elixir_aliases.erl:80: :elixir_aliases.ensure_loaded/3


Compilation failed because of a deadlock between files.
The following files depended on the following modules:

  lib/expr/parser.ex => Expr.Ops
     lib/expr/ops.ex => Expr.Ops
         lib/expr.ex => Expr.Ops

could not compile dependency :expr, "mix compile" failed. You can recompile this dependency with "mix deps.compile expr", update it with "mix deps.update expr" or clean it with "mix deps.clean expr"
```

**Comment by dongmaster** [comment]
Found the issue. The hex package is broken. However, if you add {:expr, git: "https://github.com/Rob-bie/expr.git"} to your mix.exs file, the issue will be fixed.

Thanks to José and Ben for figuring this out.

**Comment by Rob-bie** [comment]
Good call. I need to update the Hex package! I merged some PR a while ago and completely forgot about this project. 

I'm away from home right now and am on my phone but should be able to take care of this in a day or two. Thank you!
